package Prectice_Exception;

public class AllInOneException {

	public static void main(String[] args) {
		int a=5;
		int b=0;
		int c;
		String name="ram";
		String s=null;
		int arr[]= {1,2,3};
		try {
			c=a/b;
		} catch (Exception e) {
			System.out.println("ihbiullh");
		}

	}

}
